name: ACore
main: fr.skyfighttv.acore.Main
version: 5.0
api-version: 1.16
commands:
  acore:
    aliases:
      - "ac"
  asanction:
    aliases:
      - "as"
      - "sanction"
  astaff:
    aliases:
      - "staff"
      - "mod"
  artp:
    aliases:
      - "rtp"
  ahoesell: